### ISSUE TITLE
SHA1 broken?

### ISSUE THREAD

**Issue by ptman** [manuelkasper/mod_auth_pubtkt#19]
I'm not by any means knowledgeable in cryptography. But SHA1 seems to be considered deprecated for several uses. (DSA even more so). Would it make sense to add support for SHA256 and default to it?

**Comment by manuelkasper** [comment]
Yes, it would make sense... Patches are welcome :)

**Comment by tomalok** [comment]
I'm working on a patch to make the digest algorithm configurable with a `TKTAuthDigest` directive -- basically I need to update the documentation, the perl/php login scripts, and do some testing.

Without the new directive, it still defaults to SHA1 for RSA private keys, and DSS1 for DSA.  My current patch adds SHA224, SHA256, SHA384, and SHA512 -- but technically any OpenSSL digest should be able to be used.

As the current version is 0.9, I'm tempted to bump up the version to 0.10 in the patch -- or I can leave that to the maintainers, if they prefer.

**Comment by manuelkasper** [comment]
Closing as this has been fixed a long long time ago (https://github.com/manuelkasper/mod_auth_pubtkt/commit/029d7d33ebb85eb24c3c9311dd0e7a12d1c42d5f) – thanks @tomalok !
