### ISSUE TITLE
Golang implementation of auth_pubtkt

### ISSUE THREAD

**Issue by ArthurHlt** [manuelkasper/mod_auth_pubtkt#23]
Hello there,
You might interested to know that a golang implementation of this apache module (which is not anymore in this implementation) exists, it can be found here: https://github.com/orange-cloudfoundry/go-auth-pubtkt 

There is also support ticket encryption in the header or the cookie, Co-workers fork your version with this concept, I'm trying to make them create a pull request to integrate this here.

**Comment by manuelkasper** [comment]
Thanks for the information! I've added a note about this to https://neon1.net/mod_auth_pubtkt/download.html to help other people find it.

**Comment by ArthurHlt** [comment]
thank you for this add
