### ISSUE TITLE
pubtkt_generate sometimes generates wrong signature

### ISSUE THREAD

**Issue by michelcve** [manuelkasper/mod_auth_pubtkt#28]
The pubtkt_generate function sometimes results in an invalid signature (tested on php 7.2.7 on docker).

The cause for this is this line:

`$sig = fread($pipes[1], 8192);`

That should be replace with:

```
$sig = '';
while (!feof($pipes[1]))
  $sig = .= fread($pipes[1], 8192);
```

This has probably something to do with warning nr. 3 in the php manual for fread (http://php.net/manual/en/function.fread.php).

**Comment by manuelkasper** [comment]
Finally fixed – thanks!

**Comment by michelcve** [comment]
Great, thanks! Better late than never ey ;-)
