### ISSUE TITLE
X-Forwarded-Proto header is not respected for method selection in the redirect url that appended to the GET request

### ISSUE THREAD

**Issue by Ludek2** [manuelkasper/mod_auth_pubtkt#35]
If apache server is deployed behind a load balancer that provides TLS termination mod_auth_pubtkt is unable to correctly create redirect url (the one appended to the GET request) .

The request flow looks like this:

https request to LB with TLS termination ----> http request to Apache server with mod_auth_pubtkt 

This PR fixes the problem: https://github.com/manuelkasper/mod_auth_pubtkt/pull/34

**Comment by manuelkasper** [comment]
PR merged, thanks!

**Comment by Ludek2** [comment]
Thank you for merging. Any chance to create a new release and push RPM to the repo?

**Comment by manuelkasper** [comment]
I have bumped the version and created a new release on GitHub. Not sure how RPMs are pushed, as I have never done that :wink:
